#! /bin/bash -e

# Rebuild-bump: 0

rootdir=$(pwd)
result=true

info() { echo "DIFF_LINT_INFO: $*" >&2 ; }
error() { echo "DIFF_LINT_ERROR: $*" >&2 ; }

analyze_subdir()
{
    info "Linting in '$1' subdirectory"
    cd "$rootdir/$1" 2>/dev/null || {
        error "Directory '$1' not found"
        result=false
        return
    }
    vcs-diff-lint --print-fixed-errors || result=false
}

git config --global --add safe.directory '*'
git config --global advice.detachedHead false
git fetch origin main:main

test -z "$INPUT_SUBDIRECTORY" || INPUT_SUBDIRECTORIES=$INPUT_SUBDIRECTORY
test -z "$INPUT_SUBDIRECTORIES" && INPUT_SUBDIRECTORIES=.

for subdir in $INPUT_SUBDIRECTORIES; do
    analyze_subdir "$subdir"
done

$result
