#! /bin/bash -e

# Rebuild-bump: 0

rootdir=$(pwd)
result=true

error() { echo "DIFF_LINT_ERROR: $*" >&2 ; }

target_branch=${GITHUB_BASE_REF-main}

is_true() {
    [[ $# -le 0 ]] && return 1

    case "$1" in
      [tT] | [yY] | [yY][eE][sS] | [oO][nN] | [tT][rR][uU][eE] | 1)
        return 0
        ;;

      *)
        return 1
        ;;
    esac
}

is_true "$INPUT_DEBUG" && set -x

linter_options=()
set_linter_options()
{
    if is_true "$INPUT_DEBUG" || is_true "$RUNNER_DEBUG"; then
        linter_options+=( --log-level=debug )
    fi
    for tag in $INPUT_LINTER_TAGS; do
        linter_options+=( --linter-tag "$tag" )
    done
    if test "$target_branch" != main; then
        linter_options+=( --compare-against "origin/$target_branch" )
    fi
}

get_pure_defects()
{
    set +e
    if [[ -z "${linter_options[*]/--log-level=debug}" ]]; then
        vcs-diff-lint >> defects.log
    else
        vcs-diff-lint "${linter_options[@]}" >> defects.log
    fi
    set -e
}

analyze_subdir()
{
    echo
    echo "## Linting in '$1' subdirectory ##"
    echo
    cd "$rootdir/$1" 2>/dev/null || {
        error "Directory '$1' not found"
        result=false
        return
    }
    get_pure_defects
    vcs-diff-lint --print-fixed-errors "${linter_options[@]}" || result=false
}

git config --global --add safe.directory '*'
git config --global advice.detachedHead false
git fetch origin "$target_branch:$target_branch" &>/dev/null

test -z "$INPUT_SUBDIRECTORY" || INPUT_SUBDIRECTORIES=$INPUT_SUBDIRECTORY
test -z "$INPUT_SUBDIRECTORIES" && INPUT_SUBDIRECTORIES=.

set_linter_options
for subdir in $INPUT_SUBDIRECTORIES; do
    analyze_subdir "$subdir"
done

csgrep \
    --strip-path-prefix "./" \
    --mode=sarif \
    --set-scan-prop="tool:vcs-diff-lint" \
    --set-scan-prop="tool-url:https://github.com/fedora-copr/vcs-diff-lint#readme" \
    "defects.log" > output.sarif
echo "sarif=$rootdir/output.sarif" >> "${GITHUB_OUTPUT}"

$result
