#! /bin/bash -e

# Rebuild quay.io bump: 1

rootdir=$(pwd)
result=true

error() { echo "DIFF_LINT_ERROR: $*" >&2 ; }

target_branch=${GITHUB_BASE_REF-main}

is_true() {
    [[ $# -le 0 ]] && return 1

    case "$1" in
      [tT] | [yY] | [yY][eE][sS] | [oO][nN] | [tT][rR][uU][eE] | 1)
        return 0
        ;;

      *)
        return 1
        ;;
    esac
}

if is_true "$INPUT_DEBUG" || is_true "$RUNNER_DEBUG"; then
    set -x
fi

linter_options=()
set_linter_options()
{
    if is_true "$INPUT_DEBUG" || is_true "$RUNNER_DEBUG"; then
        linter_options+=( --log-level=debug )
    fi
    for tag in $INPUT_LINTER_TAGS; do
        linter_options+=( --linter-tag "$tag" )
    done
    if test "$target_branch" != main; then
        linter_options+=( --compare-against "origin/$target_branch" )
    fi
}

populate_sarif_data()
{
    vcs-diff-lint "${linter_options[@]}" | \
    csgrep \
        --strip-path-prefix ./ \
        --prepend-path-prefix "$1/" \
        >> "$rootdir/output.sarif.err" \
    || true
}

analyze_subdir()
{
    echo
    echo "## Linting in '$1' subdirectory ##"
    echo
    cd "$rootdir/$1" 2>/dev/null || {
        error "Directory '$1' not found"
        result=false
        return
    }
    populate_sarif_data "$1"
    vcs-diff-lint --print-fixed-errors "${linter_options[@]}" || result=false
}

if test -n "$INPUT_INSTALL_RPM_PACKAGES"; then
    # shellcheck disable=SC2086
    dnf install -y $INPUT_INSTALL_RPM_PACKAGES
fi

if test "$GITHUB_EVENT_NAME" = 'pull_request'; then
    git config --global --add safe.directory '*'
    git config --global advice.detachedHead false
    git config --global init.defaultBranch main

    git fetch origin "$target_branch:$target_branch" &>/dev/null

    test -z "$INPUT_SUBDIRECTORY" || INPUT_SUBDIRECTORIES=$INPUT_SUBDIRECTORY
    test -z "$INPUT_SUBDIRECTORIES" && INPUT_SUBDIRECTORIES=.

    set_linter_options
    for subdir in $INPUT_SUBDIRECTORIES; do
        analyze_subdir "$subdir"
    done
else
    touch "$rootdir/output.sarif.err"
fi

csgrep \
    --mode=sarif \
    --set-scan-prop="tool:vcs-diff-lint" \
    --set-scan-prop="tool-url:https://github.com/fedora-copr/vcs-diff-lint#readme" \
< "$rootdir"/output.sarif.err > "$rootdir"/output.sarif

echo "sarif=output.sarif" >> "${GITHUB_OUTPUT}"

$result
