---
name: VCS Diff Lint
description: Differential code linting action

branding:
  icon: check-circle
  color: blue

inputs:
  subdirectory:
    description: |
      Sub-directory to step in before the linting is performed. The
      sub-directory must contain the `.vcs-diff-lint.yml` file, or RPM spec
      file.
    required: false

  subdirectories:
    description: |
      Equivalent to `subdirectory` option, but multiplied. Space separated list
      of sub-directories to analyze. The linter is executed multiple times, for
      each sub-diretory separately.
    required: false

  linter_tags:
    description: |
      Space-separated list of linter tags (selectors) for the `vcs-diff-lint`
      utility (see the `--linter-tags` option). By default all linters are
      selected. Avaliable linter tags are `mypy`, `pylint`, `ruff`, and `python`.
    required: false
    default: "pylint"

  install_rpm_packages:
    description: |
      Space-separated list of RPM packages that are automatically installed into
      the testing environment (= Docker container).
    required: false

  debug:
    description: Turn on debugging info.
    default: 'false'
    required: false

outputs:
  sarif:
    description: 'The SARIF file containing defects'

runs:
  using: docker
  image: docker://quay.io/copr/vcs-diff-lint:latest
