---
name: VCS Diff Lint
description: Differential code linting action

branding:
  icon: check-circle
  color: blue

inputs:
  subdirectory:
    description: Sub-directory to step in, before linting is performed
    required: false

  linter_tags:
    description: |
      Comma-separated list of linter tags (selectors) for the `vcs-diff-lint`
      utility (see the `--linter-tags` option).  By default all linters are
      selected.  Avaliable linter tags are `mypy`, `pylint`, and `python`.
    required: false

  debug:
    description: Turn on debugging info.
    default: false
    required: false

runs:
  using: docker
  image: docker://quay.io/copr/vcs-diff-lint:latest
